version: '3'
services:
    backend:
        build: ./backend
        container_name: challenge-backend
        volumes:
        - "./backend/:/app/backend/"
        ports: 
            - 5000:5000
    frontend:
        build: ./frontend
        environment:
            CHOKIDAR_USEPOLLING: "true"
        container_name: challenge-frontend
        volumes:
        - "./frontend/:/app/frontend/"
        ports: 
            - 3000:3000
        stdin_open: true