version: '3'
services:
    frontend:
        build: ./frontend
        container_name: challenge-frontend
        restart: always
        stdin_open: true
        ports:
            - 3000:3000
        depends_on:
            - backend
    backend:
        build: ./backend
        container_name: challenge-backend
        ports:
            - 5000:5000